name: Tutorials
on:
  schedule:
    # 1am on wednesday (minute, hour, day, month, day-of-the-week)
    - cron:  '0 1 * * 3'

jobs:

  build-and-test:
    name: Tutorials
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          architecture: x64

      - name: install system dependencies
        run: |
          sudo ./.github/workflows/install-ubuntu-dependencies.sh

      - name: install python dependencies
        run: |
          python --version
          python -m pip install -r tutorial/requirements.txt

      - name: test tutorial notebooks
        run: |
          python tests/test-tutorials.py

